apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/ec2-user/hello   # Replace this with the path to your local storage directory on the node
  nodeAffinity:   # Add this nodeAffinity section
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-172-31-15-147.us-east-2.compute.internal   # Replace this with the name of the node where the local storage is available
